training_system/config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :trainer do
    resources :courses do
      resources :trainees, only: :show
      resources :course_subjects, only: :update
      post "start_subject"
      member do
        post "start_course"
      end
    end
    resources :user_courses, only: [:create, :destroy]
    resources :subjects
  end

  namespace :trainee do
    resources :courses do
      resources :course_subjects, only: [:show, :update]
      resources :user_course_subjects do
        member do
          put "start_subject"
        end
        resources :user_tasks, only: :update 
      end
    end
  end
end

training_system/app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
  has_many :user_course_subjects, dependent: :destroy
  has_many :course_subjects, through: :user_course_subjects
  has_many :user_course, through: :user_course_subjects

  enum status: {init: 0, in_progress: 1, finished: 2}
  delegate :name, :duration, :description, to: :subject

  scope :course_subject_start, ->(course_id){where(course_id: course_id)}
  scope :created_asc, ->{order :created_at}
end

training_system/app/controllers/trainee/base_controller.rb
class Trainee::BaseController < ApplicationController
  layout "trainee/base"
  before_action :logged_in_user
  before_action :is_trainee
end

training_system/app/controllers/trainee/course_subjects_controller.rb
class Trainee::CourseSubjectsController < Trainee::BaseController
  before_action :load_subject,
                :load_user_course,
                :load_user_course_subject,
                :load_task_subject,
                only: [:show]

  def show; end

  private

  def load_subject
    @course_subject = CourseSubject.find_by id: params[:id]
    return if @course_subject

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_user_course_subject
    @user_course_subject =
      @course_subject.user_course_subjects.find_by(
        user_course_id: @user_course.id,
        course_subject_id: @course_subject.id
      )
    return if @user_course_subject

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_user_course
    @user_course = @course_subject.user_course.find_by(user_id: current_user.id)
    return if @user_course

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_task_subject
    @task_subjects = @user_course_subject.user_tasks
  end
end

training_system/app/controllers/trainee/courses_controller.rb
class Trainee::CoursesController < Trainee::BaseController
  before_action :load_course, :load_subjects, only: :show

  def index
    course_user = current_user.courses.page(params[:page])
                              .per(Settings.courses.per_page)
    @courses = course_user.search(params[:search])
  end

  def show; end

  private

  def load_course
    @course = current_user.courses.find_by id: params[:id]
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_subjects
    @course_subjects = @course.course_subjects.page(params[:page])
                              .per(Settings.courses.per_page)
  end
end

training_system/app/controllers/trainee/user_course_subjects_controller.rb
class Trainee::UserCourseSubjectsController < Trainee::BaseController
  before_action :load_user_course,
                :load_user_course_subject,
                :check_status_user_task,
                :load_course_sb,
                only: [:update, :start_subject]

  def update
    begin
      @user_course_subject.finished!
      @user_course_subject.update!(end_date: Time.zone.now.to_date)
      flash[:success] = t "controllers.user_course_subject_controller.success"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "controllers.user_course_subject_controller.faild"
    ensure
      redirect_to trainee_course_course_subject_path @course_sb, @user_course.course.id
    end
  end

  def start_subject
    ActiveRecord::Base.transaction do
      @user_course_subject.in_progress!
      @user_course_subject.update!(start_date: Time.zone.now.to_date)
      @user_course_subject.course_subject.subject.tasks.each do |user_task|
        @user_course_subject.user_tasks.build(task_id: user_task.id).save!
      end
      flash[:success] = t "controllers.user_course_subject_controller.success"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "controllers.course_controller.assign_trainee.f"
    ensure
      redirect_to trainee_course_course_subject_path @course_sb, @user_course.course.id
    end
  end

  private

  def load_user_course_subject
    @user_course_subject = @user_course.user_course_subjects.find_by id: params[:id]
    return if @user_course_subject

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end

  def check_status_user_task
    status_subject =
      @user_course_subject.user_tasks.pluck(:status).include?("in_progress")
    return unless status_subject

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_course_course_subject_path @course_sb
  end

  def load_user_course
    @user_course = @current_user.user_courses.find_by course_id: params[:course_id]
    return if @user_course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_course_sb
   @course_sb = @user_course_subject.course_subject_id
  end
end

training_system/app/controllers/trainee/user_tasks_controller.rb
class Trainee::UserTasksController < Trainee::BaseController
  before_action :load_user_course,
                :load_user_course_subject,
                :load_user_task,
                :load_course_subject, only: :update

  def update
    begin
      @user_task.finished!
      flash[:success] = t "controllers.user_tasks_controller.success"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "controllers.user_tasks_controller.faild"
    ensure
      redirect_to trainee_course_course_subject_path @course_subject.id, @user_course.course.id
    end
  end

  private

  def load_user_task
    @user_task = @user_course_subject.user_tasks.find_by id: params[:id]
    return if @user_task

    flash[:danger] = t("controllers.user_tasks_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_course_subject
    @course_subject = @user_task.user_course_subject.try(:course_subject)
  end

  def load_user_course
    @user_course = @current_user.user_courses.find_by course_id: params[:course_id]
    return if @user_course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_user_course_subject
    @user_course_subject =
      @user_course.user_course_subjects.find_by id: params[:user_course_subject_id]
    return if @user_course_subject

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end
  
end

training_system/app/controllers/trainer/course_subjects_controller.rb
class Trainer::CourseSubjectsController < Trainer::BaseController
  before_action :load_subject, :check_all_finished, only: :update

  def update
    @course_subject.transaction do
      @course_subject.finished!
      @course_subject.update! end_date: Time.zone.now.to_date
      flash[:success] = t("controllers.course_subjects_controller.success")
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t("controllers.course_subjects_controller.fail")
    ensure
      redirect_to trainer_course_path @course.id
    end
  end

  private

  def load_subject
    load_course
    @course_subject = @course.course_subjects
                             .find_by subject_id: params[:subject_id]
    return if @course_subject

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_course
    @course = Course.find_by id: params[:course_id]
    return if @course

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def status_check course_subject, status
    course_subject.user_course_subjects
                  .pluck(:status).include?(status)
  end

  def check_all_finished
    if status_check(@course_subject, "in_progress") || status_check(@course_subject, "init")
      flash[:danger] = t("controllers.course_subjects_controller.fail")
      redirect_to trainer_course_path @course.id
    end
  end
end

training_system/app/controllers/trainer/trainees_controller.rb
class Trainer::TraineesController < Trainer::BaseController
  before_action :load_trainee, :load_user_course_subjects, :load_course, only: :show

  def show
    @course_subjects = @course.course_subjects
                              .page(params[:page])
                              .per(Settings.courses.per_page)
    load_user_course_subjects
  end

  private

  def load_trainee
    @trainee = User.find_by id: params[:id]
    return if @trainee

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end

  def load_user_course_subjects
    user_course = @trainee.user_courses.find_by(course_id: params[:course_id])
    return (@user_course_subjects = user_course.user_course_subjects) if user_course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end

  def load_course
    @course = @trainee.courses.find_by(id: params[:course_id])
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end
end

training_system/app/views/trainee/course_subjects/_subject_of_course.html.erb
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <span class="name mb-0 text-sm"><%= task_subject.name %></span>
      </div>
    </div>
  </th>
  <td class="budget">
    <%=task_subject.description %>
  </td>
  <td class="budget">
    <%= task_subject.duration %> <%= t("views.course_subject.show.date") %>
  </td>
  <td class="budget">
    <%= task_subject.status %>
  </td>
  <td class="budget">
    <%if task_subject.in_progress? %>
      <%= link_to t("views.course.show.finished"), trainee_course_user_course_subject_user_task_path(task_subject.id, user_course_subject_id: @user_course_subject.id, course_id: @user_course_subject.user_course.course.id), method: :put, class: "btn btn-info" %>
    <%end%>
  </td>
</tr>

training_system/app/views/trainee/course_subjects/show.html.erb
<div class="container-fluid mt--12">
  <div class="row mt--5">
    <div class="col-md-12 ml-auto mr-auto">
      <div class="card bg-default shadow">
        <div class="titel_show_course">
          <p class="item_title"><%= t("views.course_subject.show.header_list_subject") %></p>
          <p> <p>
          <%= link_to t("views.course.show.back"), trainee_course_path(@course_subject.course_id), class: "btn btn-info" %>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-dark table-flush">
            <thead class="thead-dark">
              <tr>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course_subject.show.name_subject") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.description") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.start_date") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.end_date") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.duration") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.status") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course_subject.show.finished") %></th>
              </tr>
            </thead>
            <tbody class="list">
              <tr>
                <th scope="row">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <span class="name mb-0 text-sm"><%= @course_subject.name %></span>
                    </div>
                  </div>
                </th>
                <td class="budget">
                  <%= @course_subject.description %>
                </td> 
                <td class="budget">
                  <%= start_date_user_course_subject(@course_subject) %>
                </td>
                  <td class="budget">
                  <%= end_date_user_course_subject(@course_subject) %>
                </td>
                <td class="budget">
                  <%= @course_subject.duration %> <%= t("views.course_subject.show.date") %> 
                </td>
                <td class="budget">
                  <%= @user_course_subject.status %>
                </td>
                <td class="budget">
                
                  <% if  @user_course_subject.init? %>
                    <%= link_to t("views.course_subject.show.start"), start_subject_trainee_course_user_course_subject_path(@user_course_subject.id, course_id: @user_course_subject.user_course.course.id), method: :put,  class: "btn btn-danger" %>
                  <% elsif check_status_user_task(@user_course_subject) && @user_course_subject.in_progress? || @user_course_subject.finished? %>
                    <span> <%= t("views.course_subject.show.btn_waiting")%> </span>
                  <% else %>
                    <%= link_to t("views.course_subject.show.finished"), trainee_course_user_course_subject_path(@user_course_subject.id, course_id: @user_course_subject.user_course.course.id ), method: :put, class: "btn btn-success" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          </div> 
        </div>
      </div>
    </div>
    <div class="card card-upgrade">
      <div class="titel_show_course">
        <p class="item_title"><%= t("views.course_subject.show.header") %></p>
        <p> <p>
      </div>
      <div class="card-body">
        <div class="table-responsive table-upgrade">
          <table class="table">
            <thead>
              <tr>
                <th class="sort"><%= t("views.course_subject.show.name") %></th>
                <th class="sort"><%= t("views.course_subject.show.descripton") %></th>
                <th class="sort"><%= t("views.course_subject.show.duration") %></th>
                <th class="sort"><%= t("views.course_subject.show.status") %></th>
                <th class="sort"><%= t("views.course_subject.show.option") %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "subject_of_course", collection: @task_subjects, as: :task_subject %>
            </tbody>
          </table>
          <hr class="my-4">
        </div>
      </div>
    </div>
  </div>