training_system/config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :trainer do
    resources :courses do
      resources :trainees, only: :show
      resources :course_subjects, only: :update
      post "start_subject"
      member do
        post "start_course"
      end
    end
    resources :user_courses, only: [:create, :destroy]
    resources :subjects
  end

  namespace :trainee do
    resources :courses do
      resources :course_subjects, only: [:show, :update]
      resources :user_course_subjects do
        member do
          put "start_subject"
        end
        resources :user_tasks, only: :update 
      end
    end
  end
end

training_system/app/views/layouts/_footer.html.erb
<footer class="footer pt-0">
  <div class="row align-items-center justify-content-lg-between">
    <div class="col-lg-6">
      <div class="copyright text-center  text-lg-left  text-muted">
        &copy; <%= I18n.t("layouts.footer.version")%>
        <%= I18n.t("layouts.footer.strong")%>
      </div>
    </div>
    <div class="col-lg-6">
      <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
          <%= I18n.t("layouts.footer.reserved")%>
        </li>
        <li class="nav-item">
          <%= I18n.t("layouts.footer.des")%>
        </li>
      </ul>
    </div>
  </div>
</footer>

training_system/app/views/layouts/_header.html.erb
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-center  ml-md-auto ">
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item">
          <span class="nav-link">
          <i class="ni ni-single-02 text-yellow"></i>
            <span class="nav-link-text">
              <% if logged_in? %>
                <%= link_to t("layouts.header.logout"), logout_path, method: :delete, class: "btn_logout" %>
              <% end %>
            </span>
          </span>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link pr-0">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold"><%= current_user.name%></span>
              </div>
            </div>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-10 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <a class="navbar-brand" href="javascript:void(0)">
                  <%= image_tag ("logo-sun.png"), class: "navbar-brand-img logo" %>
                </a> 
                <%= I18n.t("layouts.header.framgia")%>
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

training_system/app/views/layouts/_sidebar.html.erb
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="javascript:void(0)">
        <%= image_tag ("logo-sun.png"), class: "navbar-brand-img" %>
      </a>
    </div>
    <div class="navbar-inner">
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <ul class="navbar-nav">
          <li class="nav-item">
            <span class="nav-link">
              <i class="ni ni-single-02 text-primary"></i>
              <span class="nav-link-text"><%= link_to t("layouts.sidebar.course"), trainer_courses_path %></span>
            </span>
          </li>
          <li class="nav-item">
            <span class="nav-link">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text"><%= link_to t("layouts.sidebar.new_subject"), new_trainer_subject_path, method: :get %></span>
            </span>
          </li>
          <li class="nav-item">
            <span class="nav-link">
            <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">
                <% if logged_in? %>
                  <%= link_to t("layouts.sidebar.logout"), logout_path, method: :delete %>
                <% end %>
              </span>
            </span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

training_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>