training_system/config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :trainer do
    resources :courses do
      resources :trainees, only: :show
      resources :course_subjects, only: :update
      post "start_subject"
      member do
        post "start_course"
      end
    end
    resources :user_courses, only: [:create, :destroy]
    resources :subjects
  end

  namespace :trainee do
    resources :courses do
      resources :course_subjects, only: [:show, :update]
      resources :user_course_subjects do
        member do
          put "start_subject"
        end
        resources :user_tasks, only: :update 
      end
    end
  end
end

training_system/app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses, dependent: :destroy
  has_many :users, through: :user_courses
  has_many :course_subjects, dependent: :destroy
  has_many :subjects, through: :course_subjects
  enum status: {init: 0, in_progress: 1, finished: 2}
  delegate :name, :duration, to: :subjects, prefix: true

  scope :created_desc, ->{order(created_at: :desc)}
  scope :search, ->(search){where("name LIKE ?", "%#{search}%")}

  # validates :course_subjects, presence: true
  # validates :user_courses, presence: true
  validates :name, :description, :start_date, :end_date, presence: true
  validate :check_start_date_greater_current_date, if: ->{start_date.present?},
                                                   on: :create
  validate :check_end_date_is_after_start_date, if: ->{is_date_present?},
                                                on: :create

  private

  def check_start_date_greater_current_date
    return unless start_date < Time.zone.now

    errors.add(
      :base, I18n.t("courses.mess_start_date_error")
    )
  end

  def check_end_date_is_after_start_date
    return unless start_date >= end_date

    errors.add(
      :base, I18n.t("courses.mess_start_date_eq_end_date_error")
    )
  end

  def is_date_present?
    end_date.present? && start_date.present?
  end
end

training_system/app/controllers/trainee/courses_controller.rb
class Trainee::CoursesController < Trainee::BaseController
  before_action :load_course, :load_subjects, only: :show

  def index
    course_user = current_user.courses.page(params[:page])
                              .per(Settings.courses.per_page)
    @courses = course_user.search(params[:search])
  end

  def show; end

  private

  def load_course
    @course = current_user.courses.find_by id: params[:id]
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_subjects
    @course_subjects = @course.course_subjects.page(params[:page])
                              .per(Settings.courses.per_page)
  end
end

training_system/app/controllers/trainer/base_controller.rb
class Trainer::BaseController < ApplicationController
  layout "trainer/base"
  before_action :logged_in_user
  before_action :trainer_user
end

training_system/app/controllers/trainer/course_subjects_controller.rb
class Trainer::CourseSubjectsController < Trainer::BaseController
  before_action :load_subject, :check_all_finished, only: :update

  def update
    @course_subject.transaction do
      @course_subject.finished!
      @course_subject.update! end_date: Time.zone.now.to_date
      flash[:success] = t("controllers.course_subjects_controller.success")
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t("controllers.course_subjects_controller.fail")
    ensure
      redirect_to trainer_course_path @course.id
    end
  end

  private

  def load_subject
    load_course
    @course_subject = @course.course_subjects
                             .find_by subject_id: params[:subject_id]
    return if @course_subject

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def load_course
    @course = Course.find_by id: params[:course_id]
    return if @course

    flash[:danger] = t("controllers.course_subjects_controller.error_show")
    redirect_to trainee_courses_path
  end

  def status_check course_subject, status
    course_subject.user_course_subjects
                  .pluck(:status).include?(status)
  end

  def check_all_finished
    if status_check(@course_subject, "in_progress") || status_check(@course_subject, "init")
      flash[:danger] = t("controllers.course_subjects_controller.fail")
      redirect_to trainer_course_path @course.id
    end
  end
end

training_system/app/controllers/trainer/courses_controller.rb
class Trainer::CoursesController < Trainer::BaseController
  before_action :load_course, only: [:show, :edit, :update, :start_course]
  before_action :load_course_start, :load_for_start_subject, only: :start_subject
  before_action :trainee_not_course, only: :edit

  def index
    @courses = Course.created_desc.page(params[:page])
                     .per(Settings.courses.per_page)
  end

  def show
    load_trainers @course
    load_trainees @course
    load_subjects @course
  end

  def edit
    load_trainees @course
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params

    if @course.save
      flash[:success] = t "courses.create.success"
      redirect_to trainer_courses_path
    else
      render :new
    end
  end

  def update
    if @course.update course_params
      flash[:success] = t "courses.update.success"
      redirect_to trainer_course_path
    else
      flash.now[:danger] = t "courses.update.failed"
      render :edit
    end
  end

  def start_course
    begin
      @course.in_progress!
      flash[:success] = t "courses.update.success"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "courses.update.failed"
    ensure
      redirect_to trainer_courses_path
    end
  end

  def start_subject
    ActiveRecord::Base.transaction do
      @course_users.each do |course_user|
        @course_start_subject.user_course_subjects
                              .build(user_course_id: course_user.id)
      end
      @course_start_subject.save!
      @course_start_subject.in_progress!
      @course_start_subject.update!(start_date: Time.zone.now.to_date)
      flash[:success] = t "courses.update.success"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "courses.update.failed"
    ensure
      redirect_to trainer_course_path @course.id
    end
  end

  private

  def course_params
    params.require(:course).permit(
      :name, :description, :status, :start_date, :end_date,
      subject_ids: [], user_ids: []
    )
  end

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_courses_path
  end

  def load_trainers course
    @trainers = course.users.trainer.page(params[:page])
                      .per(Settings.courses.per_page)
  end

  def load_trainees course
    @trainees = course.users.trainee.page(params[:page])
                      .per(Settings.courses.per_page)
  end

  def load_subjects course
    @subjects = course.subjects.page(params[:page])
                      .per(Settings.courses.per_page)
  end

  def trainee_not_course
    trainees = @course.users.trainee.ids
    @trainees_not_course = User.trainee.user_not_course(trainees)
                               .page(params[:page])
                               .per(Settings.courses.per_page)
  end

  def load_course_start
    @course = Course.find_by id: params[:course_id]
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_courses_path
  end

  def load_for_start_subject
    @course_users = @course.user_courses
    @course_start_subject = @course.course_subjects
                                   .find_by subject_id: params[:subject_id]
    if @course_start_subject.blank?
      flash[:danger] = t("controllers.course_controller.error_show")
      redirect_to trainer_courses_path
    end
  end
end

training_system/app/controllers/trainer/subjects_controller.rb
class Trainer::SubjectsController < Trainer::BaseController
  before_action :subject_params, only: :create

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def create
    @subject = Subject.new subject_params
    @subject.transaction do
      @subject.save!
      flash[:success] = I18n.t("controllers.subject_controller.create.success")
    rescue ActiveRecord::RecordInvalid
      flash[:danger] =  I18n.t("controllers.subject_controller.create.faild")
    ensure
      render :new
    end
  end

  private

  def subject_params
    params.require(:subject)
          .permit(:name, :description, :duration,
                  tasks_attributes: [:id, :name, :description, :duration])
  end

  def check_duration
    sum_duration_task = 0
    subject_params[:tasks_attributes].each do |task|
      sum_duration_task += task[:duration].to_i
    end
    sum_duration_task
  end

  def duration_task_valid
    if check_duration > subject_params[:duration].to_i
      flash[:danger] = t "controllers.subject_controller.create.duration"
      redirect_to new_trainer_subject_path
    end
  end
end

training_system/app/controllers/trainer/trainees_controller.rb
class Trainer::TraineesController < Trainer::BaseController
  before_action :load_trainee, :load_user_course_subjects, :load_course, only: :show

  def show
    @course_subjects = @course.course_subjects
                              .page(params[:page])
                              .per(Settings.courses.per_page)
    load_user_course_subjects
  end

  private

  def load_trainee
    @trainee = User.find_by id: params[:id]
    return if @trainee

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end

  def load_user_course_subjects
    user_course = @trainee.user_courses.find_by(course_id: params[:course_id])
    return (@user_course_subjects = user_course.user_course_subjects) if user_course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end

  def load_course
    @course = @trainee.courses.find_by(id: params[:course_id])
    return if @course

    flash[:danger] = t("controllers.course_controller.error_show")
    redirect_to trainer_course_path
  end
end

training_system/app/controllers/trainer/user_courses_controller.rb
class Trainer::UserCoursesController < ApplicationController
  before_action :load_course, only: :create
  before_action :load_course_destroy, only: :destroy

  def new; end

  def edit; end

  def create
    if params[:user_ids].present?
      assign_trainee
    else
      flash[:danger] = t "controllers.course_controller.assign_trainee.f"
      redirect_to edit_trainer_course_path @course.id
    end
  end

  def destroy
    remove_trainee
  end

  private

  def load_course
    @course = Course.find_by id: params[:course_id]
    return if @course

    flash[:danger] = t "controllers.course_controller.error_show"
    redirect_to edit_trainer_course_path @course.id
  end

  def load_course_destroy
    @course_destroy = Course.find_by id: params[:id]
    return if @course_destroy

    flash[:danger] = t "controllers.course_controller.error_show"
    redirect_to edit_trainer_course_path @course.id
  end

  def assign_trainee
    @course.transaction do
      params[:user_ids].each do |user|
        @course.user_courses.build user_id: user
      end
      @course.save!
      flash[:success] = t "controllers.course_controller.assign_trainee.suc"
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = t "controllers.course_controller.assign_trainee.f"
    ensure
      redirect_to edit_trainer_course_path @course.id
    end
  end

  def remove_trainee
    trainees = User.user_in_course params[:user_ids]
    if @course_destroy.present? && trainees.present?
      trainees_destroy = @course_destroy.user_courses
                                        .user_course_in_course(trainees.ids)
      @course_destroy.transaction do
        trainees_destroy.destroy_all
        flash[:success] = t "controllers.course_controller.remove_trainee.suc"
      rescue ActiveRecord::RecordInvalid
        flash[:danger] = t "controllers.course_controller.remove_trainee.fail"
      ensure
        redirect_to edit_trainer_course_path @course_destroy.id
      end
    else
      flash[:danger] = t "controllers.course_controller.remove_trainee.fail"
      redirect_to edit_trainer_course_path @course_destroy.id
    end
  end
end

training_system/app/helpers/courses_helper.rb
module CoursesHelper
  def status_select
    Course.statuses.keys
  end

  def subject_select
    Subject.select(:id, :name)
  end

  def user_select
    User.trainee.select(:id, :name)
  end

  def check_status_user_task user_course_subject
    check_status = ["in_progress", "init"]
    (user_course_subject.user_tasks.pluck(:status) & check_status).count >= 1
  end

  def check_status_user_course_sb course_subject
    return content_tag(:span, t("helper.course.awaiting")) if course_subject.user_course_subjects.blank?

    user_course =
      course_subject.user_course.find_by(user_id: current_user.id)
    return false if user_course.blank?

    user_course_sb =
      course_subject.user_course_subjects.find_by(
                          course_subject_id: course_subject.id,
                          user_course_id: user_course.id
                        )
    return content_tag(:span, t("helper.course.awaiting")) if user_course_sb.start_date.blank?
    
    duration = course_subject.subject.try(:duration)
    time_start = user_course_sb.start_date
    time_end = user_course_sb.end_date
    time = Time.zone.now
    time_current = time.strftime("%d %B, %Y").to_date

    if user_course_sb.finished?
      status = (time_end - time_start > duration) ? "finished_beyond_time" : "finished"
    else
      status = (time_current - time_start > duration) ? "unfinished" : "in_progress"
    end
    content_tag(:span, t("helper.course.#{status}"))
  end

  def end_date_user_subject course_subject
    l(course_subject.start_date + course_subject.duration)
  end

  def user_course_subject course_subject
    user_course =
      course_subject.course.user_courses.find_by(user_id: current_user.id)
    return false if user_course.blank?

    course_subject.try(:user_course_subjects).find_by(
                        course_subject_id: course_subject.id,
                        user_course_id: user_course.id
                      )
  end

  def start_date_user_course_subject course_subject
    if course_subject.init? || user_course_subject(course_subject).start_date.blank?
      content_tag(:span, t("helper.course.awaiting"))
    else
      user_course_subject(course_subject).start_date
    end
  end

  def end_date_user_course_subject course_subject
    if course_subject.init? || user_course_subject(course_subject).start_date.blank?
      content_tag(:span, t("helper.course.awaiting"))
    else
      expected_date = user_course_subject(course_subject).start_date +
                      course_subject.subject.duration
      return expected_date if user_course_subject(course_subject).in_progress?

      return user_course_subject(course_subject).end_date if user_course_subject(course_subject).finished?
    end
  end

  def status_subject subject, course
    course_subject = subject.course_subjects.find_by(course_id: course.id)
    if course_subject.present?
      course_subject.status
    else
      content_tag(:span, t("helper.course.awaiting"))
    end
  end

  def status_subject_trainee_finished(user_course_subjects, course_subject)
    note_subject = user_course_subjects
                     .find_by(course_subject_id: course_subject.id)
    if note_subject.present?
      ( note_subject.end_date.to_date - note_subject.start_date.to_date > course_subject.duration ) ? "Finished beyond time" : "Finished"
    else
      content_tag(:span, t("helper.course.awaiting"))
    end
  end

  def start_date_end_date subject, course
    course_subject = subject.course_subjects.find_by(course_id: course.id).start_date
    if course_subject.present?
      content_tag(:span,
                  "#{l(course_subject)} -
                   #{l(course_subject + subject.duration)}(expected)")
    else
      content_tag(:span, t("helper.course.awaiting"))
    end
  end

  def start_date_end_date_finished subject, course
    course_subject = subject.course_subjects
                            .find_by(course_id: course.id)
    if course_subject.present?
      content_tag(:span,
                  "#{l(course_subject.start_date)} -
                   #{l(course_subject.end_date)}")
    else
      content_tag(:span, t("helper.course.awaiting"))
    end
  end

  def status_subject_trainee(user_course_subjects, course_subject)
    status_subject = user_course_subjects
                     .find_by(course_subject_id: course_subject.id)
    return status_subject.status if status_subject.present?
    
    content_tag(:span, t("helper.course.awaiting"))
  end
end

training_system/app/views/trainer/courses/_assign_trainee_course.html.erb
<%= form_with url: trainer_user_courses_path(@course.id), class: "form-group" do |f| %>
  
  <%= f.hidden_field :course_id, value: @course.id %>
      
  <%= f.label :traine_assign %>
  <%= f.collection_select :user_ids, @trainees_not_course, :id, :name,
    {include_blank: false, include_hidden: false},
    { multiple: true, class: "select form-control", id: "assign-trainee-select"} %>

  <div class="col-lg-6 col-5 text-right btn-courses p-3">
    <%= f.submit t("courses.form.submit"), class: "btn btn-success" %>
  </div>
<% end %>

training_system/app/views/trainer/courses/_course.html.erb
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <span class="name mb-0 text-sm"><%= course.name %></span>
      </div>
    </div>
  </th>
  <td class="budget">
    <%= l(course.start_date) %>
  </td>
  <td>
    <span class="badge badge-dot mr-4">
      <i class="bg-warning"></i>
      <span class="status"><%= course.status %></span>
    </span>
  </td>
  <td class="option_button">
    <%= link_to t("views.course.index.detail_course"), trainer_course_path(course.id),  class: "btn btn-info" %>
    <% if course.init? %>
      <%= button_to t("views.course.index.start_course"),start_course_trainer_course_path(course.id), class: "btn btn-danger"%>
    <% end %>
  </td>
</tr>

training_system/app/views/trainer/courses/_form.html.erb
<%= form_for [:trainer, @course], class: "form-group" do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :start_date %>
  <%= f.date_field :start_date, class: "form-control" %>

  <%= f.label :end_date %>
  <%= f.date_field :end_date, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
  
  <%= f.label :subject %>
  <%= f.collection_select :subject_ids, subject_select, :id, :name,
    {include_blank: false, include_hidden: false},
    { multiple: true, class: "select form-control",id: "select2-subject"} %>
      
  <%= f.label :user %>
  <%= f.collection_select :user_ids, user_select, :id, :name,
    {include_blank: false, include_hidden: false},
    { multiple: true, class: "select form-control", id: "select2-user"} %>

  <div class="col-lg-6 col-5 text-right btn-courses">
    <%= link_to I18n.t("courses.form.back"), trainer_courses_path, class: "btn btn-primary" %>
    <%= f.submit I18n.t("courses.form.submit"), class: "btn btn-success" %>
  </div>
<% end %>

training_system/app/views/trainer/courses/_remove_trainee_course.html.erb
<%= form_with url: trainer_user_course_path, method: :delete, class: "form-group" do |f| %>
  
  <%= f.hidden_field :course_id, value: @course.id %>
      
  <%= f.label :traine_remove %>
  <%= f.collection_select :user_ids, @trainees, :id, :name,
    {include_blank: false, include_hidden: false},
    { multiple: true, class: "select form-control", id: "remove-trainee-select"} %>

  <div class="col-lg-6 col-5 text-right btn-courses p-3">
    <%= f.submit t("courses.form.submit"), class: "btn btn-success" %>
  </div>
<% end %>

training_system/app/views/trainer/courses/_subject_of_course.html.erb
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <span class="name mb-0 text-sm"><%= subject.name %></span>
      </div>
    </div>
  </th>
  <td class="budget">
    <%= subject.duration %>
  </td>
  <td class="budget">
    <%= status_subject(subject, @course) %>
  </td>
  <td class="budget">
    <% if status_subject(subject, @course) == "finished" %>
      <%= start_date_end_date_finished(subject, @course) %>
    <% else %>
      <%= start_date_end_date(subject, @course) %>
    <% end %>
  </td>
  <% if @course.in_progress? %>
    <% if status_subject(subject, @course) == "init" %>
      <td class="budget">
        <%= link_to t("views.course.index.start_subject"), trainer_course_start_subject_path(subject.id, course_id: @course.id, subject_id: subject.id), method: :post, class: "btn btn-info" %>
      </td>
    <% elsif status_subject(subject, @course) == "in_progress"%>
      <td class="budget">
        <%= link_to t("views.course.index.finish_subject"), trainer_course_course_subject_path(subject.id, course_id: @course.id, subject_id: subject.id), method: :put, class: "btn btn-info" %>
      </td>
    <% end %>
  <% end %>
</tr>

training_system/app/views/trainer/courses/_trainee_of_course.html.erb
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <span class="name mb-0 text-sm"><%= trainee.name %></span>
      </div>
    </div>
  </th>
  <td class="budget">
    <%= trainee.email %>
  </td>
  <td class="budget">
    <%= link_to t("views.course.show.progress"), trainer_course_trainee_path(trainee.id, course_id: @course.id),  class: "btn btn-info" %>
  </td>
</tr>

training_system/app/views/trainer/courses/_trainer_of_course.html.erb
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <span class="name mb-0 text-sm"><%= trainer.name %></span>
      </div>
    </div>
  </th>
  <td class="budget">
    <%= trainer.email %>
  </td>
</tr>

training_system/app/views/trainer/courses/edit.html.erb
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0"><%= t "views.course.edit.header_edit" %></h3>
            </div>
          </div>
        </div>
        <div class="card-body">
          <%= form_for [:trainer, @course], class: "form-group" do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control" %>

            <%= f.label :start_date %>
            <%= f.date_field :start_date, class: "form-control" %>

            <%= f.label :end_date %>
            <%= f.date_field :end_date, class: "form-control" %>

            <%= f.label :status %>
            <%= f.select :status, status_select, {}, {class: "select form-control"} %>

            <div class="text-right btn-courses">
              <%= f.submit t("views.course.edit.save_edit"), class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="assign-table-tranee">
        <div class="assign-trainee">
          <%= render partial: "assign_trainee_course" %>
        </div>
        <div class="assign-trainee">
          <%= render partial: "remove_trainee_course" %>
        </div>
      </div>
    </div>
  </div>
</div>

training_system/app/views/trainer/courses/index.html.erb
<div class="row">
  <div class="col">
    <div class="card bg-default shadow">
      <div class="card-header bg-transparent border-0">
        <h3 class="text-white mb-0"><%= t("views.course.index.header") %></h3>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-dark table-flush">
          <thead class="thead-dark">
            <tr>
              <th scope="col" class="sort" data-sort="name"><%= t("views.course.index.name") %></th>
              <th scope="col" class="sort" data-sort="name"><%= t("views.course.index.start_date") %></th>
              <th scope="col" class="sort" data-sort="name"><%= t("views.course.index.status") %></th>
              <th scope="col" class="colspan_table" colspan="2"><%= t("views.course.index.option") %></th>
            </tr>
          </thead>
          <tbody class="list">
            <%= render @courses %>
          </tbody>
        </table>
        <div class="digg_pagination">
          <%= paginate @courses %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-6 col-5 text-right">
  <%= link_to t(".new_course"), new_trainer_course_path, class: "btn btn-success" %>
</div>

training_system/app/views/trainer/courses/new.html.erb
<div class="col-xl-12">
  <div class="card">
    <div class="card-header">
      <div class="row align-items-center">
        <div class="col-8">
          <h3 class="mb-0"> Create Course </h3>
        </div>
      </div>
    </div>
    <div class="card-body">
      <%= render "form" %>
    </div>
  </div>
</div>

training_system/app/views/trainer/courses/show.html.erb
<div class="container-fluid mt--6">
  <div class="row mt--5">
    <div class="col-md-10 ml-auto mr-auto">
      <div class="card card-upgrade">
        <div class="card-header text-center border-bottom-0">
          <h4 class="card-title"><%= t("views.course.show.header") %></h4>
          <%= link_to t("views.course.show.edit_course"), edit_trainer_course_path(@course.id), method: :get, class: "btn btn-round btn-primary" %>
        </div>
        <div class="card-body">
          <div class="table-responsive table-upgrade">
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th class="text-center"><%= t("views.course.show.content") %></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= t("views.course.show.name") %></td>
                  <td class="text-center"><%= @course.name %></td>
                </tr>
                <tr>
                  <td><%= t("views.course.show.description") %></td>
                  <td class="text-center"><%= @course.description %></td>
                </tr>
                <tr>
                  <td><%= t("views.course.show.start_date") %></td>
                  <td class="text-center"><%= l(@course.start_date) %></td>
                </tr>
                <tr>
                  <td><%= t("views.course.show.end_date") %></td>
                  <td class="text-center"><%= l(@course.end_date) %></td>
                </tr>
                <tr>
                  <td><%= t("views.course.show.status") %></td>
                  <td class="text-center"><%= @course.status %></td>
                </tr>
              </tbody>
            </table>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="card bg-default shadow">
        <div class="card-header bg-transparent border-0">
          <h3 class="text-white mb-0"><%= t("views.course.show.header_list_trainee") %></h3>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-dark table-flush">
            <thead class="thead-dark">
              <tr>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course.show.name_trainee") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course.show.email") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course.show.progress") %></th>
              </tr>
            </thead>
            <tbody class="list">
              <%= render partial: "trainee_of_course", collection: @trainees, as: :trainee %>
            </tbody>
          </table>
          <div class="digg_pagination">
            <%= paginate @trainees %>
          </div>
        </div>
      </div>
      <div class="card bg-default shadow">
        <div class="card-header bg-transparent border-0">
          <h3 class="text-white mb-0"><%= t("views.course.show.header_list_trainer") %></h3>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-dark table-flush">
            <thead class="thead-dark">
              <tr>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course.show.name_trainer") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course.show.email") %></th>
              </tr>
            </thead>
            <tbody class="list">
              <%= render partial: "trainer_of_course", collection: @trainers, as: :trainer %>
            </tbody>
          </table>
          <div class="digg_pagination">
            <%= paginate @trainers %>
          </div>
        </div>
      </div>
      <div class="card bg-default shadow">
        <div class="card-header bg-transparent border-0">
          <h3 class="text-white mb-0"><%= t("views.course.show.header_list_subject") %></h3>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-dark table-flush">
            <thead class="thead-dark">
              <tr>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course.show.name_subject") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course.show.duration") %></th>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course.show.status") %></th>
                <th scope="col" class="sort" data-sort="name"><%= t("views.course.show.start_date_end_date") %></th>
                <th scope="col" class="sort" data-sort="budget"><%= t("views.course.show.start_subject") %></th>
              </tr>
            </thead>
            <tbody class="list">
              <%= render partial: "subject_of_course", collection: @subjects, as: :subject %>
            </tbody>
          </table>
          <div class="digg_pagination">
            <%= paginate @subjects %>
          </div>
        </div>
      </div>
    </div>
  </div>